// AUDIT THE HANDOFF AGAINST REALITY.
//
// Ohad: "re-run tests on this entire conversation and anything you can reach on
// memory to check ten different times that the handoff is perfect", then "audit
// it 15 times and make sure its actually perfect", then "nothing should ever be
// lost. alll the details should be handed off to perfection".
//
// A handoff is a pile of claims. This re-derives every one it can from disk,
// git, the database, the sheet CSVs and the live hosts, and prints what does
// NOT match. It is meant to FAIL loudly - a document nobody checked is worth
// nothing, and one that has been checked is worth trusting.
//
//   node scripts/audit-handoff.mjs
import fs from 'node:fs';
import { execSync } from 'node:child_process';
import http from 'node:http';
import { createClient } from '@supabase/supabase-js';

const DOC = 'docs/HANDOFF-2026-09-06.md';
const OUT = 'docs/handoff-audit.md';
const doc = fs.readFileSync(DOC, 'utf8');
const lines = [];
const fails = [];
const say = (s) => { lines.push(s); console.log(s); };
const check = (pass, label, ok, detail) => {
  const mark = ok ? 'ok  ' : 'FAIL';
  say(`${mark} [${pass}] ${label}${detail ? '  — ' + detail : ''}`);
  if (!ok) fails.push(`[${pass}] ${label}${detail ? ' — ' + detail : ''}`);
};
const git = (c) => execSync('git ' + c, { encoding: 'utf8' }).trim();
// Prose with every "quoted span" removed: what the document ASSERTS, as
// opposed to what it quotes in order to correct or attribute it.
const unquoted = (t) => t.replace(/"[^"\n]{0,300}"/g, " ").replace(/\u201c[^\u201d\n]{0,300}\u201d/g, " ").replace(/\*[^*\n]{0,200}\*/g, " ");

say('# Handoff audit — ' + new Date().toISOString().slice(0, 16).replace('T', ' '));
say('');
say('Generated by `node scripts/audit-handoff.mjs`. Every line below was re-derived,');
say('not remembered.');
say('');
say('```');

// ---------------------------------------------------------------- pass 1
say('--- PASS 1 · git facts ---');
const head = git('rev-parse HEAD');
const ahead = git('rev-list --count master..HEAD');
const branch = git('rev-parse --abbrev-ref HEAD');
check(1, 'branch is bhbc-hebrew', branch === 'bhbc-hebrew', branch);
const stated = (doc.match(/\| HEAD \| `([0-9a-f]{7,40})`/) || [])[1] || '';
let statedIsReal = false, since = '?';
try {
  // NOT `${sha}^{commit}`: cmd.exe treats ^ as its escape character and eats it.
  if (git(`cat-file -t ${stated}`) !== 'commit') throw new Error('not a commit');
  execSync(`git merge-base --is-ancestor ${stated} HEAD`, { stdio: 'ignore' });
  statedIsReal = true;
  since = git(`rev-list --count ${stated}..HEAD`);
} catch { /* not a commit on this branch */ }
check(1, 'the sha the doc states is a real commit on this branch', statedIsReal, stated.slice(0, 12));
check(1, 'HEAD has not moved far since the doc was written', statedIsReal && Number(since) <= 3,
  `${since} commit(s) since — re-run this audit and update §3 if that grows`);
const statedCount = Number(((doc.match(/\*\*([0-9,]+) commits\*\*/) || [])[1] || '0').replace(/,/g, ''));
check(1, 'the commit count in the doc is current within 3', Math.abs(Number(ahead) - statedCount) <= 3,
  `doc says ${statedCount.toLocaleString('en-US')}, actual ${Number(ahead).toLocaleString('en-US')}`);
const stat = git('diff --shortstat master..HEAD');
const files = (stat.match(/(\d+) files? changed/) || [])[1];
const statedFiles = Number(((doc.match(/\*\*([0-9,]+) files/) || [])[1] || '0').replace(/,/g, ''));
check(1, 'the file count in the doc is current within 5', Math.abs(Number(files) - statedFiles) <= 5,
  `doc says ${statedFiles}, actual ${files}`);

// ---------------------------------------------------------------- pass 2
say('');
say('--- PASS 2 · every path named in the handoff exists ---');
const paths = [...new Set((doc.match(/(?:src|scripts|docs|audit-out)\/[A-Za-z0-9_./*-]+/g) || []))]
  .filter((p) => !p.includes('*') && !p.endsWith('/'))
  // this file is what the audit WRITES; it cannot be a precondition of itself
  .filter((p) => p !== OUT)
  // 'docs/handoff/01..10' is prose for a range of files, not a file
  .filter((p) => !/\/[0-9]+(\.\.[0-9]+)?$/.test(p));
let missing = 0;
for (const p of paths) {
  const ok = fs.existsSync(p);
  if (!ok) { missing++; check(2, 'path exists', false, p); }
}
check(2, `${paths.length} paths checked`, missing === 0, missing ? `${missing} missing` : 'all present');

// ---------------------------------------------------------------- pass 3
say('');
say('--- PASS 3 · every script named runs its own usage line ---');
const added = ['scripts/bhbc-log-lift.mjs', 'scripts/build-bhbc-replan.mjs', 'scripts/build-tonight.mjs',
  'scripts/serve-page.mjs', 'scripts/shoot-prod-vs-branch.mjs', 'scripts/audit-handoff.mjs'];
const scripts = paths.filter((p) => /\.(mjs|cjs)$/.test(p)).filter((p) => added.includes(p) || p.startsWith('audit-out/'));
for (const p of scripts) {
  const src = fs.readFileSync(p, 'utf8');
  const hasHeader = /^\/\//.test(src.trim());
  const hasUsage = /\/\/\s+(DRY=1\s+)?[A-Z_]*=?.*node (scripts|audit-out)\//.test(src) || /^\/\/.*\n(\/\/.*\n)*/.test(src);
  check(3, `${p} documents itself`, hasHeader && hasUsage, hasHeader ? '' : 'no header comment');
}

// ---------------------------------------------------------------- pass 4
say('');
say('--- PASS 4 · the local hosts answer ---');
const ping = (port) => new Promise((resolve) => {
  const req = http.get({ host: '127.0.0.1', port, path: '/', timeout: 4000 }, (res) => { res.resume(); resolve(String(res.statusCode)); });
  req.on('error', () => resolve('down'));
  req.on('timeout', () => { req.destroy(); resolve('timeout'); });
});
for (const [port, what] of [[4179, 'recap'], [4180, 'replan'], [4181, 'tonight']]) {
  const code = await ping(port);
  check(4, `:${port} (${what}) responds`, code === '200', code);
}

// ---------------------------------------------------------------- pass 5
say('');
say('--- PASS 5 · the database says what the handoff says ---');
const sb = createClient('https://gtcbfglttoiyfsnfbhdy.supabase.co', 'sb_publishable_i_ifflCFMUF7rX2ABAY3vA_5JKTmFlv', { auth: { persistSession: false } });
const auth = await sb.auth.signInWithPassword({ email: 'ohadyproductions@gmail.com', password: '1234' });
check(5, 'owner can sign in', !auth.error, auth.error ? auth.error.message : '');
const get = async (k) => (await sb.from('store').select('value').eq('key', k).maybeSingle()).data?.value ?? null;
const roster = (await get('expo-bhbc-roster')) || [];
const fixtures = (await get('expo-bhbc-fixtures')) || [];
const loads = (await get('expo-bhbc-loads')) || {};
check(5, 'roster is 10', roster.length === 10, String(roster.length));
check(5, 'fixtures are 33', fixtures.length === 33, String(fixtures.length));
check(5, 'NO fixture carries contactMin (the trial was restored)',
  fixtures.filter((f) => f && f.contactMin).length === 0, String(fixtures.filter((f) => f && f.contactMin).length));
const nameOf = (id) => (roster.find((r) => r.id === id) || {}).name || id;
const lifts = [];
for (const [id, rec] of Object.entries(loads)) {
  for (const [d, rows] of Object.entries((rec && rec.sessions) || {})) {
    for (const r of rows) if (/^(lift|weights)$/i.test(String(r.type || ''))) lifts.push({ d, who: nameOf(id), min: r.min, rpe: r.rpe, load: r.load });
  }
}
check(5, 'lift sessions total is 72', lifts.length === 72, String(lifts.length));
const today = lifts.filter((l) => l.d === '2026-09-06');
check(5, 'two lifts logged on 2026-09-06', today.length === 2, today.map((l) => `${l.who} ${l.min}min`).join(', '));
check(5, 'both are 30 minutes', today.every((l) => l.min === 30), today.map((l) => l.min).join('/'));
check(5, 'no lift carries an invented RPE or load', lifts.every((l) => (l.rpe == null || l.rpe === 0) && !l.load),
  String(lifts.filter((l) => l.rpe || l.load).length) + ' with a value');
const sep1 = lifts.filter((l) => l.d === '2026-09-01');
check(5, 'the handoff states the roster and fixture counts correctly',
  doc.includes(`roster ${roster.length} · fixtures ${fixtures.length}`),
  `roster ${roster.length} · fixtures ${fixtures.length}`);
check(5, 'the handoff states the lift-session total correctly',
  doc.includes(`${lifts.length} lift sessions`), `${lifts.length} lift sessions`);
check(5, '1 Sep is 9 lifters × 12 min = 108, as the UI line says',
  sep1.length === 9 && sep1.reduce((a, l) => a + l.min, 0) === 108,
  `${sep1.length} lifters, ${sep1.reduce((a, l) => a + l.min, 0)} min`);

// ---------------------------------------------------------------- pass 6
say('');
say('--- PASS 6 · the memory this handoff points at exists ---');
const MEM = 'C:/Users/Administrator/.claude/projects/C--Users-Administrator-Desktop-expo-full/memory';
for (const m of ['MEMORY.md', 'project_bhbc_replan_2026_09_06.md', 'project_handoff_2026_09_06.md']) {
  check(6, `memory/${m}`, fs.existsSync(`${MEM}/${m}`));
}
const index = fs.readFileSync(`${MEM}/MEMORY.md`, 'utf8');
const top3 = index.split('\n').slice(0, 3).join(' ');
check(6, 'the resume trigger and tonight are both at the top of MEMORY.md',
  /feedback_pita_protocol\.md/.test(top3) && /project_bhbc_replan_2026_09_06\.md/.test(top3),
  index.split('\n')[0].slice(0, 60));
check(6, 'the bbq restore trigger is still indexed', /bbq/i.test(index));

// ---------------------------------------------------------------- pass 8
say('');
say('--- PASS 8 · every value quoted from his sheet is in the CSV ---');
const aug = fs.readFileSync('audit-out/bhbc-sheet/August.csv', 'utf8');
const feb = fs.readFileSync('audit-out/bhbc-sheet/February.csv', 'utf8');
const sep = fs.readFileSync('audit-out/bhbc-sheet/September.csv', 'utf8');
for (const [what, hay, needle] of [
  ['84 Min practice', aug, '84 Min'],
  ['13 Min contact', aug, '13 Min'],
  ['15.5% density', aug, '15.5%'],
  ['Low Intensity band', aug, 'Low Intensity'],
  ['9 Players', aug, '9 Players'],
  ['Q1 quadrant', aug, 'Q1'],
  ['the availability index', aug, 'No Restriction'],
  ['Out - Medical', aug, 'Out - Medical'],
  ['Basketball Plan', aug, 'Basketball Plan'],
  ['Density scale legend', aug, 'Under 20%'],
  ['high-volume rule', aug, 'Above 90 Min'],
  ['Q4 legend wording', aug, 'Moderate Volume & High Intensity'],
  ['February S&C content', feb, 'BW Strength'],
  ['PT Notes lane', sep, 'PT Notes'],
  ['the #DIV/0! his sheet prints', sep, '#DIV/0!'],
]) {
  check(8, what, hay.includes(needle), needle);
}
check(8, 'August and September carry a PT lane', aug.includes('PT Notes') && sep.includes('PT Notes'));
check(8, 'February does NOT (S&C lane only)', !feb.includes('PT Notes'), feb.includes('PT Notes') ? 'still there' : 'confirmed');
// The five months must be five DIFFERENT months. A tab click that does not
// switch tabs once wrote February into all five files, and nothing noticed.
const months = ['August', 'September', 'October', 'January', 'February'].map((m) => ({ m, csv: fs.readFileSync(`audit-out/bhbc-sheet/${m}.csv`, 'utf8') }));
const sizes = months.map((x) => x.csv.length);
check(8, 'the five months are five distinct files', new Set(sizes).size === 5, sizes.join(' / '));
check(8, 'August is the tab the quotes come from', months[0].csv.includes('20/08/2025'));
// the note lanes, counted the same way the handoff counts them
const noteCounts = months.map(({ m, csv }) => {
  const rows = csv.split(String.fromCharCode(10));
  const h = rows.findIndex((r) => r.includes('PT Notes') || r.includes('S & C Notes'));
  if (h < 0) return { m, cols: 0, filled: 0 };
  const cols = rows[h].split(',').map((c, i) => ({ c: c.replace(/"/g, '').trim(), i })).filter((x) => /PT Notes|S & C Notes/.test(x.c));
  let filled = 0;
  for (const r of rows.slice(h + 1)) { const cells = r.split(','); for (const x of cols) { if ((cells[x.i] || '').replace(/"/g, '').trim()) filled++; } }
  return { m, cols: cols.length, filled };
});
for (const { m, cols, filled } of noteCounts) {
  check(8, `${m}: note lanes as the handoff states`, doc.includes(`| ${m} | ${cols} | ${filled} |`), `${cols} columns, ${filled} filled`);
}
check(8, 'five month tabs on disk',
  ['August', 'September', 'October', 'January', 'February'].every((m) => fs.existsSync(`audit-out/bhbc-sheet/${m}.csv`)));

// ---------------------------------------------------------------- pass 9 (static half)
say('');
say('--- PASS 9 · the code really does what the handoff claims ---');
const bhbc = fs.readFileSync('src/BhbcView.jsx', 'utf8');
const he = fs.readFileSync('src/bhbcHe.js', 'utf8');
const dates = fs.readFileSync('src/dates.js', 'utf8');
for (const [what, hay, needle] of [
  ['the Weight Room tab is registered', bhbc, "['weightroom', tr('Weight Room')]"],
  ['future days are not columns', bhbc, 'if (iso > today) break;'],
  ['available-players row is counted', bhbc, 'const availPerDay'],
  ['what the room did is built from sessions', bhbc, 'const roomDays = useMemo(() => days.list.map'],
  ['density returns null without both numbers', bhbc, 'if (!min || !con) return null;'],
  ['his density bands', bhbc, "{ max: 25, key: 'Moderate Intensity'"],
  ['the quadrant is derived', bhbc, "const quadrant = highIntensity ?"],
  ['the load board gates its columns', bhbc, 'const hasLoad = rows.some'],
  ['the sessions panel can render bare', bhbc, 'if (bare) return inner;'],
  ['Team Snapshot is conditional', bhbc, '{(team.avg != null || (team.week || 0) > 0) && <TeamSnapshotCard'],
  ['Hebrew for the weight room', he, 'חדר כוח'],
  ['Hebrew months', dates, 'MONTH_NAMES_HE'],
  ['the numeric date is untouched', dates, "return `${p(d.getDate())}/${p(d.getMonth() + 1)}/${d.getFullYear()}`;"],
]) {
  check(9, what, hay.includes(needle), needle.slice(0, 46));
}
check(9, 'the S&C Brief is gone from Overview', !bhbc.includes('<CoachBrief rows={rows}'));
check(9, 'Next Game is gone from Overview but still on Schedule',
  (bhbc.match(/<NextGamePanel/g) || []).length === 1, String((bhbc.match(/<NextGamePanel/g) || []).length) + ' occurrence(s)');
// It DOES differ from master - an earlier session on this branch. The claim
// that matters is that tonight's work did not touch a file the athlete app
// shares.
const touchedTonight = git('log --since="2026-09-05 20:00" --name-only --format= -- src/readinessAutoreg.js').trim();
check(9, 'readinessAutoreg.js untouched TONIGHT', touchedTonight === '', touchedTonight || 'no commit tonight touched it');
// unquoted(): the break-test table QUOTES the lie it plants, and a quoted lie
// is evidence, not a claim.
const raLines = unquoted(doc).split(String.fromCharCode(10)).filter((l) => /readinessAutoreg/.test(l));
check(9, 'the handoff mentions the shared file at all', raLines.length > 0, `${raLines.length} line(s)`);
const raWrong = raLines.filter((l) => /rewritten|edited|changed|modified|updated/i.test(l));
check(9, 'EVERY line about it says it was not touched tonight',
  raWrong.length === 0 && raLines.some((l) => /not touched tonight/i.test(l)),
  raWrong[0] ? raWrong[0].slice(0, 80) : '');
check(9, 'no forbidden word in the new UI strings',
  !/\b(cure|diagnose)\b/i.test(he), 'bhbcHe.js');

// ---------------------------------------------------------------- pass 10
say('');
say('--- PASS 10 · the open questions are still open ---');
check(10, 'nothing from this branch is on master', git('branch --contains HEAD --list master') === '', 'master does not contain HEAD');
check(10, 'the handoff lists the deploy decision as open', /Deploy or not/.test(doc));
check(10, 'the Q4 legend question is recorded', /Moderate Volume/.test(doc));
check(10, 'the demo probe still carries its warning',
  fs.readFileSync('audit-out/probe-demo-dates.mjs', 'utf8').includes('NOT TRUSTED YET'));


// ---------------------------------------------------------------- pass 11
say('');
say('--- PASS 11 · the ten lens handoffs, and no contradictions ---');
const LENSES = ['01-newcomer', '02-auditor', '03-owner', '04-end-users', '05-data', '06-qa', '07-design', '08-request-ledger', '09-risk', '10-next-shift'];
let lensText = "";
for (const l of LENSES) {
  const p = `docs/handoff/${l}.md`;
  const ok = fs.existsSync(p);
  check(11, `docs/handoff/${l}.md`, ok);
  if (ok) lensText += fs.readFileSync(p, "utf8");
}
// A number that appears in a lens must agree with the master. These are the
// canonical facts everything else is built on.
const CANON = [
  ['roster size', /roster[^.]{0,20}\b10\b|\b10\b[^.]{0,20}athletes/i],
  ['fixtures', /\b33\b/],
  ['lift sessions', /\b72\b/],
  ['the Hebrew word count', /147/],
  ['the dashboard card count', /seven|7 cards/i],
];
for (const [what, re] of CANON) {
  check(11, `the master states ${what}`, re.test(doc), '');
}
// nothing in a lens may claim a contradicting version of the two numbers most
// likely to drift
check(11, 'no lens ASSERTS the roster is 11', !/roster is 11|roster 11/i.test(unquoted(lensText)));
check(11, 'nothing ASSERTS 428 files', !/428 files/.test(unquoted(lensText + doc)));

// ---------------------------------------------------------------- pass 12
say('');
say('--- PASS 12 · every request in the ledger carries a status ---');
const ledger = doc.slice(doc.indexOf('## 14 · The request ledger'), doc.indexOf('## 15 ·'));
const rows = ledger.split(String.fromCharCode(10)).filter((l) => /^\| *[0-9]+ *\|/.test(l));
check(12, 'the ledger has rows', rows.length >= 30, `${rows.length} rows`);
const STATUS = /(done|partial|open|cancelled by him|pacing)/i;
const statusless = rows.filter((r) => !STATUS.test(r.split("|").slice(3).join("|")));
check(12, 'every row has a status', statusless.length === 0, statusless.slice(0, 2).join(' // '));
// his own words must be quoted, not paraphrased
const quoted = rows.filter((r) => /"/.test(r)).length;
check(12, 'the rows quote him directly', quoted >= rows.length - 2, `${quoted}/${rows.length} quote him`);

// ---------------------------------------------------------------- pass 13
say('');
say('--- PASS 13 · the resume word is registered everywhere ---');
const WORD = 'pita';
check(13, 'the handoff names the word', new RegExp('`' + WORD + '`').test(doc), WORD);
const memFile = `${MEM}/feedback_pita_protocol.md`;
check(13, 'a memory file defines it', fs.existsSync(memFile));
check(13, 'MEMORY.md indexes it', /feedback_pita_protocol\.md/.test(index));
if (fs.existsSync(memFile)) {
  const mf = fs.readFileSync(memFile, "utf8");
  check(13, 'the memory file says do not deploy', /do not deploy/i.test(mf));
  check(13, 'the memory file points at this handoff', /HANDOFF-2026-09-06\.md/.test(mf));
}

// ---------------------------------------------------------------- pass 14
say('');
say('--- PASS 14 · no weasel words ---');
// A handoff that hedges is a handoff nobody can act on. Each of these was a
// real defect in an earlier draft.
const WEASEL = [
  ['probably', /\bprobably\b/i],
  ['should be (unverified)', /\bshould be fine\b|\bshould work\b/i],
  ['I think', /\bI think\b/i],
  ['almost always', /\balmost always\b/i],
  ['roughly, without a number', /\broughly\b(?![^.]{0,40}[0-9])/i],
];
for (const [what, re] of WEASEL) {
  const prose = unquoted(doc);
  check(14, `no "${what}" outside a quotation`, !re.test(prose), (prose.match(re) || [''])[0]);
}

// ---------------------------------------------------------------- pass 15
say('');
say('--- PASS 15 · every command block names something that exists ---');
const blocks = doc.match(/```bash[\s\S]*?```/g) || [];
check(15, 'the handoff carries command blocks', blocks.length >= 4, `${blocks.length} blocks`);
const named = [...new Set((blocks.join(String.fromCharCode(10)).match(/(?:scripts|audit-out)\/[A-Za-z0-9_.-]+\.(?:mjs|cjs)/g) || []))];
let ghosts = 0;
for (const p of named) {
  if (!fs.existsSync(p)) { ghosts++; check(15, `command names a missing script`, false, p); }
}
check(15, `${named.length} scripts named in commands all exist`, ghosts === 0, ghosts ? `${ghosts} missing` : 'all present');

say('```');
say('');
say(fails.length ? `## ${fails.length} thing(s) the audit did not confirm` : '## Everything the audit could check, checked out');
for (const f of fails) say(`- ${f}`);
fs.writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`\n-> ${OUT}`);
process.exit(fails.length ? 1 : 0);
