// Shared exercise dictionary for Client Portal + Workout Review
// Single source of truth — add new client exercises here only
// Keys: eid strings matching ClientPortal CLIENTS references

export const EX = {
  // === Diego Day (t1) — Block #9 ===
  e1:{t:"Prone Laying Around the World",vid:"https://www.youtube.com/watch?v=cwLZOh5SInQ"},
  e2:{t:"90/90 POS Rear-Leg Heel-Clicks",vid:"https://www.youtube.com/shorts/cduSxyjDql8"},
  e3:{t:"Dead-Bug POS Elbow Floor-Slide",vid:"https://www.youtube.com/watch?v=ZtcpBztji78"},
  e4:{t:"Bear-POS Shoulder Taps",vid:"https://www.youtube.com/shorts/_ENCgTck-yk"},
  e5:{t:"ISO Kneeling Push-Up",vid:"https://www.youtube.com/shorts/N5Nqb4qBmJ8"},
  e6:{t:"90-90 Get Ups",vid:"https://www.youtube.com/watch?v=lWf78Bf-rAI"},
  e7:{t:"ISO Kossac Squat",vid:"https://www.youtube.com/shorts/-GKJ_enu4WM"},
  e8:{t:"ABs Sit-Up w Twist",vid:"https://www.youtube.com/watch?v=Lje-oV4CsW8"},
  e9:{t:"Machine Leg Extension",vid:"https://www.youtube.com/shorts/fP6uMgfwqOA"},
  e10:{t:"BB Lunge"},
  e11:{t:"BB Pedlay Row"},
  e12:{t:"Machine Incline Chest-Press"},
  e13:{t:"Machine Leg Curl"},
  e14:{t:"Standing Arnold DB OHP"},

  // === Ron Yonker (t2) — Block #13 ===
  e29:{t:"Push-Up Tantrum",vid:"https://www.youtube.com/shorts/vdioRdJEZtk"},
  e30:{t:"Banded Power Pallof Press",vid:"https://www.youtube.com/shorts/uYpjXMkAUOY"},
  e31:{t:"HOZ Board Jump SL Landing",vid:"https://www.youtube.com/watch?v=Owe3pjT1oiw"},
  e32:{t:"BB FFESS",vid:"https://www.youtube.com/shorts/gAceC8CKSRU",q:"\u05E8\u05D0\u05E9 \u05DE\u05E2\u05DC \u05D4\u05D1\u05E8\u05DA. \u05D4\u05DE\u05E9\u05E7\u05DC \u05E2\u05DC \u05D4\u05E8\u05D2\u05DC \u05D4\u05E7\u05D3\u05DE\u05D9\u05EA. \u05DC\u05D0\u05E0\u05D2' \u05E7\u05E6\u05E8."},
  e33:{t:"BB Bench Press",vid:"https://www.youtube.com/shorts/bvaCXyXeBvU",q:"\u05DB\u05E4\u05D5\u05EA \u05E8\u05D2\u05DC\u05D9\u05D9\u05DD \u05DE\u05EA\u05D7\u05EA \u05DC\u05D9\u05E9\u05D1\u05DF. \u05E2\u05E7\u05D1 \u05E0\u05D3\u05D7\u05E3 \u05DC\u05E8\u05E6\u05E4\u05D4."},
  e34:{t:"Elbow-Supported SA DB Row",vid:"https://www.youtube.com/watch?v=1i2iXHBGAro",q:"\u05DB\u05E3 \u05D4\u05D9\u05D3 \u05DB\u05DC\u05E4\u05D9 \u05D4\u05EA\u05E7\u05E8\u05D4. \u05DE\u05E8\u05E4\u05E7 \u05DC\u05E2\u05D1\u05D5\u05E8 \u05D0\u05EA \u05D4\u05D2\u05D5\u05E3."},
  e35:{t:"Hip-Thrust POS DB Pullover",vid:"https://www.youtube.com/shorts/Oo2YRiyp378"},
  e36:{t:"Short-Lever ABs Sit-Up",vid:"https://www.youtube.com/shorts/EvAup1z42-s"},
  e37:{t:"FFESS to Lunge POGO Jump"},
  e38:{t:"Alt SL Squat POGO"},
  e39:{t:"Power SL Hip-Thrust Catch"},
  e40:{t:"BB Deficit Jefferson DL",vid:"https://www.youtube.com/watch?v=r2kzdEd1sHk"},
  e41:{t:"Seated BB OHP",vid:"https://www.youtube.com/watch?v=mJkSxRn70yw"},
  e42:{t:"DB Goblet Squat",vid:"https://www.youtube.com/shorts/EzsUhxczCpM"},
  e43:{t:"SA Cable Pulldown"},
  e44:{t:"Elbow-Supported DB Knee Raise",vid:"https://www.youtube.com/watch?v=cYZgZrZtaGE"},

  // === Omer Sadeh (t3) — Block #7 ===
  e50:{t:"DB Squat Jump",vid:"https://www.youtube.com/shorts/LE2WYrSEyZI",q:"רד למצב שאתה ברבע סקוואט, ותעצור שם. לא המשכי! משקולת בכל יד"},
  e51:{t:"BB Pendlay Row",vid:"https://www.youtube.com/shorts/IhiF9i9s8NI",q:"סט אפ של דדליפט. לדחוף את האגן עוד קצת אחורה. משקל כבד!"},
  e52:{t:"Hand-Release Power Push-Up",vid:"https://www.youtube.com/shorts/Q0O7BWiQ1FE",q:"תרים את הידיים. בטן מכווצת. פיצוץ עם הידיים כנגד הרצפה"},
  e53:{t:"Continuous Power SL Hip-Thrust",vid:"https://www.youtube.com/shorts/dwNigaxVq4g",q:"מתחילים מהרצפה. עקב בלבד דוחף את הרצפה. תרגיל פליאומטרי"},
  e54:{t:"Alternating DB Chest Press",vid:"https://www.youtube.com/watch?v=MM4oFyRYeqg",q:"המשקולות ב-90 מעלות. סט-אפ של בנץ'. שמור משקולת קרובה לגוף"},
  e55:{t:"Half-Kneeling SA Cable Row",vid:"https://www.youtube.com/watch?v=4QDCC2gU5_E",q:"היד שחותרת בצד הנגדי לרגל הקדמית. משיכה למטה ואחורה!"},
  e56:{t:"DB AB's Sit-Up + Leg Raise (Clam)",vid:"https://www.youtube.com/watch?v=sutOFgNFX_A",q:"תנועה של צדפה שנסגרת. כפיפת בטן + הרמת רגליים. נפגשים באמצע"},
  e57:{t:"Deep-Squat POGO Jump",vid:"https://www.youtube.com/shorts/NE2Ctrd2fsY",q:"קפיצות המשכיות במצב סקוואט עמוק"},
  e58:{t:"Standing VERT Jump to SL Landing",vid:"https://www.youtube.com/watch?v=PNHkYbSd49w",q:"קפיצה לגובה. מרפקים מובילים. נחיתה על רגל אחת"},
  e59:{t:"Continuous SL VERT Jump to Snap-Down",vid:"https://www.youtube.com/shorts/vdioRdJEZtk",q:"קפיצה לגובה מרגל אחת + סנאפ דאון. קצב קבוע"},
  e60:{t:"BB/DB Jefferson DL",vid:"https://www.youtube.com/watch?v=7GBBkA60Yu8",q:"ראש מתחיל את התנועה. ברכיים ישרות אך לא נעולות. משקל קרוב לגוף"},
  e61:{t:"SA Cable Pulldown",vid:"https://www.youtube.com/watch?v=bCjRRJ2lI8Y",q:"סיבוב מלא של כף היד. משוך כתף + מרפק לרצפה"},
  e62:{t:"Machine Chest-Supported Row",vid:"https://www.youtube.com/watch?v=7oqpWiwSjtY",q:"בית חזה על הספה. תנועה מלאה. אחיזה MID-POS"},
  e63:{t:"Machine Leg Extension",vid:"https://www.youtube.com/shorts/fP6uMgfwqOA",q:"ישיבה עם זווית סקוואט. משקל תמיד באוויר. פלקס חזק"},
  e64:{t:"ISO GHD AB Sit-Up w 90° Twist",vid:"https://www.youtube.com/watch?v=p1bpeNYhUKc",q:"כפות ידים על האוזניים. מרפקים רחוקים. ראש מסתובב עם הגוף"},
  e65:{t:"B-Stance DB Fast ECC DL",vid:"https://www.youtube.com/watch?v=tAvwbyE2nWc",q:"ליפול הכי מהר שאפשר ולתפוס. עקב אחורית באוויר. משקל על עקב קדמית"},
  e66:{t:"Band-Resisted SL Snap-Down",vid:"https://www.youtube.com/shorts/2nFwe8IHgic",q:"עמידה על קצות אצבעות. סנאפ דאון נמוך, נחיתה על רגל אחת"},
  e67:{t:"Tall-Kneeling OH MED-Ball Fake Slam",vid:"https://www.youtube.com/watch?v=mXCBGe88CvI",q:"שתי ברכיים על הרצפה. ישבן רחוק מעקבים. תבלום ברגע אחת"},
  e68:{t:"Standing MED-Ball Lateral Fake Toss",vid:"https://www.youtube.com/shorts/HZRyu5Whf7A",q:"מרפקים ישרים. סובב אגן + בטן לכיוון הקיר. תבלום ברגע אחת"},
  e69:{t:"Walking DB Lunge",vid:"https://www.youtube.com/watch?v=VG12H7tYnZ8",q:"משקולת בכל יד. בית חזה לרצפה. כף רגל עוברת על הרצפה כמו צעד רגיל"},
  e70:{t:"Wide-Pronated HOZ Cable Row",vid:"https://www.youtube.com/watch?v=mNqH5_a-trw",q:"אחיזה רחבה. ברכיים נעולות. ישבן רחוק מהכבל. הרפייה מלאה"},
  e71:{t:"Dead-Bug POS DB Pullover",vid:"https://www.youtube.com/watch?v=Wg2Z2hYxB0c",q:"ברכיים באוויר מעל הפופיק. גב תחתון צמוד. שלח אחורה רחוק"},
  e72:{t:"ISO Pronated Dead-Hang Leg Raise",vid:"https://www.youtube.com/watch?v=Ri9unVtgUK8",q:"מתח בנים. אגודלים למעלה. ברכיים לא נעולות. פלקס בכפות רגליים"},

  // === Yuval Barko (t4) — Comeback Block ===
  e100:{t:"BB Elevated-Heel Back Squat",vid:"https://www.youtube.com/watch?v=fv1LX_brEmM"},
  e101:{t:"BB Close-Grip Bench Press",vid:"https://www.youtube.com/watch?v=XEFDMwmrLAM"},
  e102:{t:"ISO Chin-Up",vid:"https://www.youtube.com/watch?v=i27qYZjRCLg"},
  e103:{t:"DB Unilateral RFESS",vid:"https://www.youtube.com/watch?v=tKEsinm0j1E",q:"רגל קדמית גם מוגבהת?"},
  e104:{t:"Push-Up POS DB SA Row",vid:"https://www.youtube.com/watch?v=mg9-Z19XEk0"},
  e105:{t:"Prone Laying ISO Knee Raise",vid:"https://www.youtube.com/watch?v=VEfA6YzvMW8"},
  e106:{t:"ISO Long-Lever Hip-Thrust",vid:"https://www.youtube.com/watch?v=OX8SJVGinuI"},
  e107:{t:"BB B-Stance RDL",vid:"https://www.youtube.com/watch?v=fI_TYwBHne0"},
  e108:{t:"DB Step-Up",vid:"https://www.youtube.com/watch?v=37tVohr7LcE"},
  e109:{t:"Standing Alternating DB OHP",vid:"https://www.youtube.com/watch?v=yQg0mHo-fjQ"},
  e110:{t:"Floor Seating HOZ Cable Row",vid:"https://www.youtube.com/watch?v=drBclSNfdn8"},
  e111:{t:"DB Chest Press (Feet on Bench)",vid:"https://www.youtube.com/watch?v=vE_0-aGOBLs"},
  e112:{t:"Laying DB Pullover (Floating Feet)",vid:"https://www.youtube.com/watch?v=7ee9w2zYFr0"},
  e113:{t:"Short-Lever ABs Sit-Up",vid:"https://www.youtube.com/shorts/EvAup1z42-s"},
  e114:{t:"90/90 POS ISO Rear Foot Raise",vid:"https://www.youtube.com/shorts/p5xNWdyBey4"},
  e115:{t:"90/90 POS ISO Rear Leg Raise",vid:"https://www.youtube.com/shorts/p5xNWdyBey4"},
  e116:{t:"90/90 POS Thorasic Rotation",vid:"https://www.youtube.com/watch?v=nVMK9LxL8HI"},
  e117:{t:"BW FFESS",vid:"https://www.youtube.com/shorts/h2bgbzdrl-c"},
  e118:{t:"VERT Jump to SL Landing",vid:"https://www.youtube.com/shorts/jQ2Z7sSfibM"},
  e119:{t:"Multi-Directional POGO Jump (Soft Landing)",vid:"https://www.youtube.com/shorts/2DYc5n4oCko"},
  e120:{t:"Push-Up POS Knee to Opposite Elbow",vid:"https://www.youtube.com/watch?v=eGZPjAqV9OM"},
};
