// Shared exercise dictionary for Client Portal + Workout Review
// Single source of truth — add new client exercises here only
// Keys: eid strings matching ClientPortal CLIENTS references

export const EX = {
  // === Diego Day (t1) — Block #9 ===
  e1:{t:"Prone Laying Around the World",vid:"https://www.youtube.com/watch?v=cwLZOh5SInQ"},
  e2:{t:"90/90 POS Rear-Leg Heel-Clicks",vid:"https://www.youtube.com/shorts/cduSxyjDql8"},
  e3:{t:"Dead-Bug POS Elbow Floor-Slide",vid:"https://www.youtube.com/watch?v=ZtcpBztji78"},
  e4:{t:"Bear-POS Shoulder Taps",vid:"https://www.youtube.com/shorts/_ENCgTck-yk"},
  e5:{t:"ISO Kneeling Push-Up",vid:"https://www.youtube.com/shorts/N5Nqb4qBmJ8"},
  e6:{t:"90-90 Get Ups",vid:"https://www.youtube.com/watch?v=lWf78Bf-rAI"},
  e7:{t:"ISO Kossac Squat",vid:"https://www.youtube.com/shorts/-GKJ_enu4WM"},
  e8:{t:"ABs Sit-Up w Twist",vid:"https://www.youtube.com/watch?v=Lje-oV4CsW8"},
  e9:{t:"Machine Leg Extension",vid:"https://www.youtube.com/shorts/fP6uMgfwqOA"},
  e10:{t:"BB Lunge"},
  e11:{t:"BB Pedlay Row"},
  e12:{t:"Machine Incline Chest-Press"},
  e13:{t:"Machine Leg Curl"},
  e14:{t:"Standing Arnold DB OHP"},

  // === Ron Yonker (t2) — Block #13 ===
  e29:{t:"Push-Up Tantrum",vid:"https://www.youtube.com/shorts/vdioRdJEZtk"},
  e30:{t:"Banded Power Pallof Press",vid:"https://www.youtube.com/shorts/uYpjXMkAUOY"},
  e31:{t:"HOZ Board Jump SL Landing",vid:"https://www.youtube.com/watch?v=Owe3pjT1oiw"},
  e32:{t:"BB FFESS",vid:"https://www.youtube.com/shorts/gAceC8CKSRU",q:"\u05E8\u05D0\u05E9 \u05DE\u05E2\u05DC \u05D4\u05D1\u05E8\u05DA. \u05D4\u05DE\u05E9\u05E7\u05DC \u05E2\u05DC \u05D4\u05E8\u05D2\u05DC \u05D4\u05E7\u05D3\u05DE\u05D9\u05EA. \u05DC\u05D0\u05E0\u05D2' \u05E7\u05E6\u05E8."},
  e33:{t:"BB Bench Press",vid:"https://www.youtube.com/shorts/bvaCXyXeBvU",q:"\u05DB\u05E4\u05D5\u05EA \u05E8\u05D2\u05DC\u05D9\u05D9\u05DD \u05DE\u05EA\u05D7\u05EA \u05DC\u05D9\u05E9\u05D1\u05DF. \u05E2\u05E7\u05D1 \u05E0\u05D3\u05D7\u05E3 \u05DC\u05E8\u05E6\u05E4\u05D4."},
  e34:{t:"Elbow-Supported SA DB Row",vid:"https://www.youtube.com/watch?v=1i2iXHBGAro",q:"\u05DB\u05E3 \u05D4\u05D9\u05D3 \u05DB\u05DC\u05E4\u05D9 \u05D4\u05EA\u05E7\u05E8\u05D4. \u05DE\u05E8\u05E4\u05E7 \u05DC\u05E2\u05D1\u05D5\u05E8 \u05D0\u05EA \u05D4\u05D2\u05D5\u05E3."},
  e35:{t:"Hip-Thrust POS DB Pullover",vid:"https://www.youtube.com/shorts/Oo2YRiyp378"},
  e36:{t:"Short-Lever ABs Sit-Up",vid:"https://www.youtube.com/shorts/EvAup1z42-s"},
  e37:{t:"FFESS to Lunge POGO Jump"},
  e38:{t:"Alt SL Squat POGO"},
  e39:{t:"Power SL Hip-Thrust Catch"},
  e40:{t:"BB Deficit Jefferson DL",vid:"https://www.youtube.com/watch?v=r2kzdEd1sHk"},
  e41:{t:"Seated BB OHP",vid:"https://www.youtube.com/watch?v=mJkSxRn70yw"},
  e42:{t:"DB Goblet Squat",vid:"https://www.youtube.com/shorts/EzsUhxczCpM"},
  e43:{t:"SA Cable Pulldown"},
  e44:{t:"Elbow-Supported DB Knee Raise",vid:"https://www.youtube.com/watch?v=cYZgZrZtaGE"},

  // === Omer Sadeh (t3) — Block #7 ===
  e50:{t:"DB Squat Jump",vid:"https://www.youtube.com/shorts/LE2WYrSEyZI",q:"רד למצב שאתה ברבע סקוואט, ותעצור שם. לא המשכי! משקולת בכל יד"},
  e51:{t:"BB Pendlay Row",vid:"https://www.youtube.com/shorts/IhiF9i9s8NI",q:"סט אפ של דדליפט. לדחוף את האגן עוד קצת אחורה. משקל כבד!"},
  e52:{t:"Hand-Release Power Push-Up",vid:"https://www.youtube.com/shorts/Q0O7BWiQ1FE",q:"תרים את הידיים. בטן מכווצת. פיצוץ עם הידיים כנגד הרצפה"},
  e53:{t:"Continuous Power SL Hip-Thrust",vid:"https://www.youtube.com/shorts/dwNigaxVq4g",q:"מתחילים מהרצפה. עקב בלבד דוחף את הרצפה. תרגיל פליאומטרי"},
  e54:{t:"Alternating DB Chest Press",vid:"https://www.youtube.com/watch?v=MM4oFyRYeqg",q:"המשקולות ב-90 מעלות. סט-אפ של בנץ'. שמור משקולת קרובה לגוף"},
  e55:{t:"Half-Kneeling SA Cable Row",vid:"https://www.youtube.com/watch?v=4QDCC2gU5_E",q:"היד שחותרת בצד הנגדי לרגל הקדמית. משיכה למטה ואחורה!"},
  e56:{t:"DB AB's Sit-Up + Leg Raise (Clam)",vid:"https://www.youtube.com/watch?v=sutOFgNFX_A",q:"תנועה של צדפה שנסגרת. כפיפת בטן + הרמת רגליים. נפגשים באמצע"},
  e57:{t:"Deep-Squat POGO Jump",vid:"https://www.youtube.com/shorts/NE2Ctrd2fsY",q:"קפיצות המשכיות במצב סקוואט עמוק"},
  e58:{t:"Standing VERT Jump to SL Landing",vid:"https://www.youtube.com/watch?v=PNHkYbSd49w",q:"קפיצה לגובה. מרפקים מובילים. נחיתה על רגל אחת"},
  e59:{t:"Continuous SL VERT Jump to Snap-Down",vid:"https://www.youtube.com/shorts/vdioRdJEZtk",q:"קפיצה לגובה מרגל אחת + סנאפ דאון. קצב קבוע"},
  e60:{t:"BB/DB Jefferson DL",vid:"https://www.youtube.com/watch?v=7GBBkA60Yu8",q:"ראש מתחיל את התנועה. ברכיים ישרות אך לא נעולות. משקל קרוב לגוף"},
  e61:{t:"SA Cable Pulldown",vid:"https://www.youtube.com/watch?v=bCjRRJ2lI8Y",q:"סיבוב מלא של כף היד. משוך כתף + מרפק לרצפה"},
  e62:{t:"Machine Chest-Supported Row",vid:"https://www.youtube.com/watch?v=7oqpWiwSjtY",q:"בית חזה על הספה. תנועה מלאה. אחיזה MID-POS"},
  e63:{t:"Machine Leg Extension",vid:"https://www.youtube.com/shorts/fP6uMgfwqOA",q:"ישיבה עם זווית סקוואט. משקל תמיד באוויר. פלקס חזק"},
  e64:{t:"ISO GHD AB Sit-Up w 90° Twist",vid:"https://www.youtube.com/watch?v=p1bpeNYhUKc",q:"כפות ידים על האוזניים. מרפקים רחוקים. ראש מסתובב עם הגוף"},
  e65:{t:"B-Stance DB Fast ECC DL",vid:"https://www.youtube.com/watch?v=tAvwbyE2nWc",q:"ליפול הכי מהר שאפשר ולתפוס. עקב אחורית באוויר. משקל על עקב קדמית"},
  e66:{t:"Band-Resisted SL Snap-Down",vid:"https://www.youtube.com/shorts/2nFwe8IHgic",q:"עמידה על קצות אצבעות. סנאפ דאון נמוך, נחיתה על רגל אחת"},
  e67:{t:"Tall-Kneeling OH MED-Ball Fake Slam",vid:"https://www.youtube.com/watch?v=mXCBGe88CvI",q:"שתי ברכיים על הרצפה. ישבן רחוק מעקבים. תבלום ברגע אחת"},
  e68:{t:"Standing MED-Ball Lateral Fake Toss",vid:"https://www.youtube.com/shorts/HZRyu5Whf7A",q:"מרפקים ישרים. סובב אגן + בטן לכיוון הקיר. תבלום ברגע אחת"},
  e69:{t:"Walking DB Lunge",vid:"https://www.youtube.com/watch?v=VG12H7tYnZ8",q:"משקולת בכל יד. בית חזה לרצפה. כף רגל עוברת על הרצפה כמו צעד רגיל"},
  e70:{t:"Wide-Pronated HOZ Cable Row",vid:"https://www.youtube.com/watch?v=mNqH5_a-trw",q:"אחיזה רחבה. ברכיים נעולות. ישבן רחוק מהכבל. הרפייה מלאה"},
  e71:{t:"Dead-Bug POS DB Pullover",vid:"https://www.youtube.com/watch?v=Wg2Z2hYxB0c",q:"ברכיים באוויר מעל הפופיק. גב תחתון צמוד. שלח אחורה רחוק"},
  e72:{t:"ISO Pronated Dead-Hang Leg Raise",vid:"https://www.youtube.com/watch?v=Ri9unVtgUK8",q:"מתח בנים. אגודלים למעלה. ברכיים לא נעולות. פלקס בכפות רגליים"},

  // === Yuval Barko (t4) — Comeback Block ===
  e100:{t:"BB Elevated-Heel Back Squat",vid:"https://www.youtube.com/watch?v=fv1LX_brEmM",q:"תעמוד על הגבהה קטנה לעקבים! בית חזה לרצפה ושמירה על זווית כל הסט. מרפקים מתקרבים אחד לשני (גב מכווץ) ללא הפסקה! משקל על כל כף הרגל"},
  e101:{t:"BB Close-Grip Bench Press",vid:"https://www.youtube.com/watch?v=XEFDMwmrLAM",q:"מרפקים צמודים לגוף. רגליים מתחת לישבן, וארבע ראשי שעובד ללא הפסקה (עקב לרצפה). תשאיר את המרפק מתחת לשורש כף היד"},
  e102:{t:"ISO Chin-Up",vid:"https://www.youtube.com/watch?v=i27qYZjRCLg",q:"כמה שיותר גבוה, כמה שיותר קדימה. כתפיים נוגעות במוט. ראש עובר את המוט קדימה"},
  e103:{t:"DB Unilateral RFESS",vid:"https://www.youtube.com/watch?v=tKEsinm0j1E",q:"משקולת בצד אחד ובאותו הצד של הרגל האחורית. בית חזה נטוי כלפי הרצפה (משקולת מעבר לברך). ברך יורדת למטה ואחורה"},
  e104:{t:"Push-Up POS DB SA Row",vid:"https://www.youtube.com/watch?v=mg9-Z19XEk0",q:"רק משקולת אחת, יד שנייה על הרצפה. ישבן גבוה. ברכיים נעולות. בטן לא מסתובבת. מרפק עולה עד הסוף"},
  e105:{t:"Prone Laying ISO Knee Raise",vid:"https://www.youtube.com/watch?v=VEfA6YzvMW8",q:"שתי רגליים!! לא כמו בסרטון. שכיבה על הבטן. ראש על הרצפה. ידיים ישרות על הרצפה ליד הישבן. תרים כפות רגליים וכופף את הברך עד שכף הרגל מעל הברך. דחוף בפלקס כלפי התקרה"},
  e106:{t:"ISO Long-Lever Hip-Thrust",vid:"https://www.youtube.com/watch?v=OX8SJVGinuI"},
  e107:{t:"BB B-Stance RDL",vid:"https://www.youtube.com/watch?v=fI_TYwBHne0",q:"עקב אחורית באוויר. משקל על העקב של הרגל הקדמית. הגב לא צריך לרדת, הישבן צריך להידחף אחורה ולמעלה!"},
  e108:{t:"DB Step-Up",vid:"https://www.youtube.com/watch?v=37tVohr7LcE",q:"כל כף הרגל על ההגבה. כל המשקל על העקב בדחיפה למעלה. דחוף ברך קדימה ואז תעלה. סיים את כל החזרות ואז תחליף רגל!"},
  e109:{t:"Standing Alternating DB OHP",vid:"https://www.youtube.com/watch?v=yQg0mHo-fjQ",q:"עמידה רחבה פי 2 מעמידה של סקוואט. ברכיים נעולות וישבן מכווץ. תשאיר במידל פוזישן כל התנועה. שמור על המרפק בקו של החזה"},
  e110:{t:"Floor Seating HOZ Cable Row",vid:"https://www.youtube.com/watch?v=drBclSNfdn8",q:"פתח פיסוק רחב. ברכיים ישרות אך לא נעולות. הרפייה מלאה כשהמשקל עדיין באוויר. בטן נשארת במקום, הכתפיים והגב העליון זזים. פלקס בכף הרגל"},
  e111:{t:"DB Chest Press (Feet on Bench)",vid:"https://www.youtube.com/watch?v=vE_0-aGOBLs",q:"כפות רגליים על הספה, צמודות לישבן. 45 מעלות, לא מיד פוזישן, ולא בנץ'! מרפק נשאר תמיד מתחת לשורש כף היד. סט-אפ של בנץ'"},
  e112:{t:"Laying DB Pullover (Floating Feet)",vid:"https://www.youtube.com/watch?v=7ee9w2zYFr0",q:"ברכיים באוויר מעל הפופיק. גב תחתון צמוד לספה. מרפקים ישרים אך לא נעולים. שלח את המשקולת כמה שיותר אחורה, לא רק למטה"},
  e113:{t:"Short-Lever ABs Sit-Up",vid:"https://www.youtube.com/shorts/EvAup1z42-s",q:"עקבים כמה שיותר קרובים לישבן. רגליים מקובעות מתחת למשהו כבד. ידיים כלפי התקרה כל הזמן. כפיפת בטן מלאה עד לישיבה, תסיים כשאתה מאונך לקרקע"},
  e114:{t:"90/90 POS ISO Rear Foot Raise",vid:"https://www.youtube.com/shorts/p5xNWdyBey4",q:"הברך נשארת על הרצפה. פלג גוף עליון זקוף. תשתמש בכפות ידיים כדי להתנגד לתזוזה עם הרצפה. תמשוך את כף הרגל האחורית כלפי התקרה בפלקס. עקב לכיוון התקרה"},
  e115:{t:"90/90 POS ISO Rear Leg Raise",vid:"https://www.youtube.com/shorts/p5xNWdyBey4",q:"כמו החלק השני בסרטון, סטטי. פלג גוף עליון זקוף. תשתמש בכפות ידיים כדי להתנגד לתזוזה עם הרצפה. עקב לכיוון התקרה"},
  e116:{t:"90/90 POS Thorasic Rotation",vid:"https://www.youtube.com/watch?v=nVMK9LxL8HI",q:"שב ב-90-90 על הרצפה. כף יד נגדית לרגל הקדמית על הראש, ומרפק רחוק מהפנים. נסה להגיע עם המרפק לנקודה ברצפה מתחת לבית השחי. תוציא אוויר לקראת הרצפה"},
  e117:{t:"BW FFESS",vid:"https://www.youtube.com/shorts/h2bgbzdrl-c",q:"הגבהה לרגל הקדמית. משקל על אמצע/מרכז כף הרגל הקדמית. מבט למטה. טווח תנועה מלא בירידה ועלייה!"},
  e118:{t:"VERT Jump to SL Landing",vid:"https://www.youtube.com/shorts/jQ2Z7sSfibM",q:"קפיצה לגובה מהמקום. מרפקים מובילים תנועה כלפי מעלה. נחיתה על רגל אחת בלבד (בלי תיקונים)"},
  e119:{t:"Multi-Directional POGO Jump (Soft Landing)",vid:"https://www.youtube.com/shorts/2DYc5n4oCko",q:"זמן מגע קצר מאוד עם הרצפה. מכת הצלפה עם כף הרגל ברצפה. בלי הרבה תנועה בברכיים. תזוז מהאגן, רגליים רפויות באוויר ומתכווצות לקראת המגע עם הרצפה"},
  e120:{t:"Push-Up POS Knee to Opposite Elbow",vid:"https://www.youtube.com/watch?v=eGZPjAqV9OM",q:"ישבן קצת יותר גבוה משאר הגוף. ראש למטה. ברגל שנשארת על הרצפה, הברך נעולה. כף רגל שעובדת, בפלקס"},

  // === Shalev Lugashi (t5) — Block #7 ===
  // Day A
  e200:{t:"BW High Step-Up",vid:"https://www.youtube.com/watch?v=KGyVfgh0fhk",q:"קופסא הכי גבוהה שאתה יכול. עקב חזק על הקופסא. בית חזה מול הרצפה (משקל על הרגל הקדמית). סיים סט ואז תחליף רגל"},
  e201:{t:"MID-POS Chin-Up",vid:"https://www.youtube.com/shorts/LMDKMvNuB6s",q:"חמש שניות תלייה במצב רפוי. חמש שניות החזקה למעלה, כשהכתפיים נוגעות במוט. טווח תנועה מלא. ראש בין הידיים בשיא ההרפייה, ומרפקים ליד האוזניים"},
  e202:{t:"Alternating UNI/IPSI KB SLDL",vid:"https://www.youtube.com/watch?v=-wNUNK0BH1Q",q:"קטלבל ביד אחת, ירידה לדדליפט על רגל אחת, מניח על הרצפה ומרים ביד השנייה. עקב באוויר. ברכיים ישרות לא נעולות. בית חזה כמה שיותר רחוק מהרצפה"},
  e203:{t:"SL Hip-Thrust POS DB Pullover",vid:"https://www.youtube.com/watch?v=YucEdhbUAgQ",q:"מצב היפ טראסט על רגל אחת, כל כף הרגל על הרצפה. בלי הקשתה בגב. ידיים ישרות מרפקים לא נעולים. תוריד כמה שיותר רחוק מהראש. משקל מת על הרצפה כל חזרה"},
  e204:{t:"Machine SL Calf Raise",vid:"https://www.youtube.com/watch?v=UdSBmZMcMvw",q:"שב בלאנג' עם ברך אחת על הרצפה. חצי מכף הרגל הקדמית על מדרגה. עליות תאומים בטווח תנועה מלא. משקל על הקצה של הברך"},
  e205:{t:"Seated (NO Back-Support) DB Bicep Curl",vid:"https://www.youtube.com/shorts/ObM9zmjj8HU"},
  e206:{t:"ISO SA Plank",vid:"https://www.youtube.com/watch?v=dVYwg0PeRqk"},
  // Day B
  e207:{t:"Standing MID-POS DB OHP",vid:"https://www.youtube.com/watch?v=M2rwvNhTOu0",q:"משקולות במיד-פוזישן. עמידה רחבה כמו עם מוט. ישבן ובטן ננעלים אחרי הנשימה. ראש נדחף קדימה ומגיעים למצב של מרפקים נעולים ליד האוזניים"},
  e208:{t:"DB Kossac Squat",vid:"https://www.youtube.com/shorts/ZJxIfjX2_oo",q:"משקולת בשתי ידיים צמודה לחזה. כל המשקל על העקב של הרגל שיורדים לכיוונה, אבל כל כף הרגל על הרצפה. להרים את האצבעות של הרגל הרחוקה"},
  e209:{t:"Bird-Dog DB SA Row",vid:"https://www.youtube.com/watch?v=zYHZm9_HJsw",q:"רגל נגדית באוויר. פלקס ברגל שבאוויר, וברך נעולה. חתירה בהרפייה מלאה מעבר לראש"},
  e210:{t:"Machine SL Curl",vid:"https://www.youtube.com/shorts/bGH1IJz1hSE",q:"רגל אחת בלבד עובדת. תחזיק עם הידיים רחוק מהגוף, כדי שהכתפיים יהיו בהרחקה קדימה, לא רוצים שהגב תחתון ייכנס להקשתה. פלקס בכף הרגל שעובדת"},
  e211:{t:"Seated HOZ MID-POS Cable Row",vid:"https://www.youtube.com/shorts/Q2FD828aNek",q:"אגודלים כלפי מעלה. ברכיים נעולות, ישבן רחוק מהכבל. הרפייה מלאה. בטן נשארת במקום, הכתפיים והגב העליון זזים. פלקס בכף הרגל"},
  e212:{t:"Laying DB Skullcrusher",vid:"https://www.youtube.com/watch?v=8aSeE4Nhr4Y",q:"סוף התנועה היא קצת מאחורי הראש, ככה השריר עובד על הסט. מרפקים לא זזים. נעילה מלאה. רגליים על הספה, עקב צמוד לישבן"},
  e213:{t:"Wall-Supported DB Lateral Raise",vid:"https://www.youtube.com/shorts/3vFAn8FJ6RY",q:"רבע סקוואט רפוי עם הגב על הקיר, תישען על הקיר! להרים קצת מעל הראש. זרתות לכיוון התקרה בהרמה. כתפיים יורדות ושמוטות בהרפייה"},
  // Day C
  e214:{t:"Dead-Bug POS DB Chest Press",vid:"https://www.youtube.com/watch?v=vjCfHgZbWR8",q:"כפות רגליים באוויר, וברכיים מקופלות מעל הפופיק. משקולות בצורת חץ. מרפק נשאר תמיד מתחת לשורש כף היד. כתפיים זזות כמו בחתירה"},
  e215:{t:"Elevated Reverse DB Lunge",vid:"https://www.youtube.com/watch?v=L80de7G3kBU",q:"עומדים על הגבהה או מדרגה. כל פעם שלח רגל אחת אחורה ללאנג'. משקולות בשתי הידיים. בית חזה לרצפה. המשקולות נשארות קדמית לגוף. נחיתה וירידה חלקות"},
  e216:{t:"BB Deficit RDL",vid:"https://www.youtube.com/watch?v=bJNCRt23nKo",q:"תעמוד על באמפר/מדרגה. כמה שפחות כפיפה בברך. ככל שהתחת הולך יותר אחורה > אנחנו משתפרים בתרגיל. רד עד שהמוט בגובה של הגרביים בערך"},
  e217:{t:"Inclined Chest-Supported Pronated DB Front-Raise",vid:"https://www.youtube.com/watch?v=Vc3-5xCXv_M",q:"שב עם החזה על הספה, פטמות באוויר. אנחנו מתעסקים בכתף שזזה אחורה וקדימה. ההרמה היא עד גובה העיניים, תרחיק את הזרועות כמה שיותר קדימה"},
  e218:{t:"SL Wall Sit",vid:"https://www.youtube.com/shorts/s-VVPq1Vpqo"},
  e219:{t:"Seated SL Calf Raise",vid:"https://www.youtube.com/watch?v=MSOfx7QrFrg",q:"שב על כסא/קופסא. כפות הרגליים על מדרגה (רק הכריות והאצבעות). טווח תנועה מלא בקרסול, גם בפלקס וגם בפויינט. שוק מאונכת לרצפה"},
  e220:{t:"ISO Chin-Up + Knee Raise",vid:"https://www.youtube.com/watch?v=9JDG4i1Mco8"},
  // Day D
  e221:{t:"ISO BB Bench Press",vid:"https://www.youtube.com/shorts/HrHTP04jKCU",q:"כפות רגליים מתחת לישבן. עקב נדחף לרצפה. שכמות כמה שיותר קרובות אחת לשנייה. מרפק מתחת לשורש כף היד"},
  e222:{t:"ISO Chest-Supported Wide-Pronated DB Row",vid:"https://www.youtube.com/shorts/7UkBOZpCNtU",q:"שכב על הבטן על ספה. מרפקים רחוקים מהגוף. מרפק נמשך כמה שיותר למעלה בכיווץ. בלי הקשתה בצוואר"},
  e223:{t:"ISO Prone-Lying Ipsilateral Superman",vid:"https://www.youtube.com/shorts/F97OdvMRs7w",q:"שכיבה על הבטן. רגליים וראש רפויים על הרצפה. שתי ידיים ישרות כלפי מעלה. רק יד אחת מתרוממת ורק רגל אחת מתרוממת! אותו הצד! מרפק מוביל. אגודלים כלפי התקרה"},
  e224:{t:"Plank Stance Knee to Elbow + Opposite Elbow",vid:"https://www.youtube.com/watch?v=dq9r3RUSyIE",q:"מצב פלאנק. נגיעה אחת עם הברך במרפק אחד, ואז נגיעה נוספת במרפק השני. ברך אחת נעולה. בטן לרצפה (בלי להסתובב), וישבן לא זז בכלל"},
  e225:{t:"Crab-POS Raise",vid:"https://www.youtube.com/shorts/HRN5DJKrVL0",q:"שב על הרצפה. ידיים מתחת לכתפיים. עקבים בלבד על הרצפה. תרים את האגן עד שאתה בקו ישר, מהברך עד הכתפיים, כמו בהיפ-טראסט"},
  e226:{t:"Supine-Lying External-Rotation",vid:"https://www.youtube.com/shorts/daMOhhSFhZE",q:"שכב על הגב. תרים רגליים באוויר, ברכיים מעל הפופיק. המרפקים הם הציר, לא זזים. המטרה להגיע עם שורש כף היד והמרפקים לרצפה ולהחזיק כמה שיותר קרוב"},
  e227:{t:"Wall-Assisted 90-90 Rear-Foot Heel-Clicks",vid:"https://www.youtube.com/shorts/cduSxyjDql8",q:"שתי ידיים על הקיר, מרפקים נעולים. פלג גוף עליון כמה שיותר זקוף! נגיעה עם העקב ליד האגן. נגיעה של הברך כשכף הרגל עדיין מורמת באוויר (ללא הקשתה גב!)"},
  e228:{t:"Short-Lever ABs Sit-Up",vid:"https://www.youtube.com/shorts/EvAup1z42-s",q:"עקבים כמה שיותר קרובים לישבן. רגליים מקובעות מתחת למשהו כבד. ידיים כלפי התקרה כל הזמן. כפיפת בטן מלאה עד לישיבה, תסיים כשאתה מאונך לקרקע"},
  // === Diego Morning Routine ===
  e3001:{t:"Declined Push-Up SCAP Protraction/Retraction",vid:"https://www.youtube.com/watch?v=NKekqeudgWs",q:"Push-up position, feet elevated. Elbows locked. 1) Retract and lower scaps. 2) Protract and raise scaps."},
  e3002:{t:"ISO Prone-Laying SA Y-Raise",vid:"https://www.youtube.com/shorts/UqTdjV17_ss",q:"Lay on belly. Raise only one arm off the floor. Thumb points to ceiling."},
  e3003:{t:"Inclined BB Supinated Push-Up",vid:"https://www.youtube.com/watch?v=F4c0GC2QMa4",q:"You control incline. Palms facing face (supinated). Elbows close to body. Elbow always above wrist."},
  e3004:{t:"ISO Kneeling Push-Up",vid:"https://www.youtube.com/shorts/N5Nqb4qBmJ8",q:"Control depth, pain max 3/10. Feet floating close to butt. Elbows close, hide armpit. Elbows and shoulders above wrists."},
  e3005:{t:"Banded Elbow Wall-Slide",vid:"https://www.youtube.com/watch?v=kXXF73vevuw",q:"Constant band tension. Full elbow lockout. Forearms against wall at all times."},
  e3006:{t:"Crab-POS Raise",vid:"https://www.youtube.com/shorts/HRN5DJKrVL0",q:"Sit on floor, hands beneath shoulders. Only heels touch floor. Raise hips to straight line, knees to shoulders."},
  e3007:{t:"ISO Prone-Laying MID-POS A Raise",vid:"https://www.youtube.com/shorts/2i48ShBwl3k",q:"Lay on belly. Lift pinkies toward ceiling. Raise arms off floor. Hands higher than elbows."},
  e3008:{t:"Supine-Lying External-Rotation",vid:"https://www.youtube.com/shorts/daMOhhSFhZE",q:"Lay on back, knees above belly. Elbows are pivot (don't move). Wrists straight with forearms. Bring wrists and elbows to floor, hold active contraction."},
  e3009:{t:"Prone-Laying Neck Hold",vid:"https://www.youtube.com/shorts/UsNvYtfTGHY",q:"Hands close to hips, palms facing floor. Chin down and back. Hold at end range."},
};
