import P from 'puppeteer-core';
const BASE='http://127.0.0.1:4173';
const W=Number(process.env.W||390);
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
const b=await P.connect({browserURL:'http://127.0.0.1:9223',defaultViewport:null,protocolTimeout:300000});
const pg=await b.newPage();
const cdp=await pg.createCDPSession();
await cdp.send('Network.setBypassServiceWorker',{bypass:true}).catch(()=>{});
await pg.setViewport({width:W,height:900,deviceScaleFactor:2,isMobile:true,hasTouch:true});
await pg.goto(BASE+'/login',{waitUntil:'domcontentloaded'});
await pg.evaluate(()=>{try{localStorage.clear();localStorage.setItem('expo-lang','he');localStorage.setItem('expo-install-snooze-until',String(Date.now()+864e5));}catch(e){}});
await pg.goto(BASE+'/login',{waitUntil:'domcontentloaded'});
await wait(3500);
await pg.evaluate(()=>{const ins=[...document.querySelectorAll('input')];const set=(el,v)=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));};const e=ins.find(i=>/email/i.test(i.type+i.placeholder+i.name));const p=ins.find(i=>i.type==='password');if(e)set(e,'ohadyproductions@gmail.com');if(p)set(p,'1234');});
await wait(400);
await pg.evaluate(()=>{const x=[...document.querySelectorAll('button')].find(y=>/^\s*(sign\s*in|כניסה)\s*$/i.test(y.textContent||''));if(x)x.click();});
await wait(10000);
await pg.evaluate(()=>{const b2=[...document.querySelectorAll('button')].find(x=>/coach|מאמן/i.test((x.textContent||'').trim()));if(b2)b2.click();});
await wait(4000);
await pg.goto(BASE+(process.env.ROUTE||'/coach'),{waitUntil:'domcontentloaded'});
await wait(11000);
const needle=process.env.NEEDLE||'חוב (';
const info=await pg.evaluate((n)=>{
  const hit=[...document.querySelectorAll('div')].find(el=>(el.textContent||'').includes(n)&&el.scrollWidth-el.clientWidth>8);
  if(!hit)return 'not found';
  const wide=[...hit.querySelectorAll('*')].map(el=>({t:el.tagName,c:String(el.className||'').slice(0,20),w:Math.round(el.getBoundingClientRect().width),sw:el.scrollWidth,txt:(el.textContent||'').replace(/\s+/g,' ').trim().slice(0,26)})).filter(x=>x.w>hit.clientWidth-2).slice(0,6);
  return {outer:hit.outerHTML.slice(0,500),clientW:hit.clientWidth,scrollW:hit.scrollWidth,wide};
},needle);
console.log(JSON.stringify(info,null,1).slice(0,2200));
await pg.close();b.disconnect();
